{% set name = "pyunlocbox" %}
{% set version = "0.6.1" %}
{% set sha256 = "4f6885947c34060aa9cfe6f0c10fbdd837647732e251dd7e7555900716fa84a4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - scipy

test:
  imports:
    - pyunlocbox
  commands:
    - python -m unittest pyunlocbox.tests.test_all.suite

about:
  home: https://github.com/epfl-lts2/pyunlocbox
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Convex Optimization in Python using Proximal Splitting'
  doc_url: https://pyunlocbox.readthedocs.io/
  dev_url: https://github.com/epfl-lts2/pyunlocbox

extra:
  recipe-maintainers:
    - mdeff
