travis:
  secure:
    BINSTAR_TOKEN: O8VVmtRixCoPgB6play4xcwO6bNhAqMacJ7BCLc67l55uzbuMA66EuNl4JFh4M/o+DaYR2IVrtIQ/oXuhPMkfgEYwlleyesaQhCOHrXT+kHOGzHBVlNTLomiRboH0lkf5GwuNuNzx3vMFoSnhAP4E5zf6CkarqTr4Kz+x5Wnab/GUTi2SZmDwYesmClnmB/ES58GtLLI69KwpbKPgwyFTWk8HBOmATZzBfIBgWpNsymvYtFw3dPSUqpz8TtYGuGQ9ZxUoo0kn3p3WQcfQ1ppi7cuNJqnopGOrUc1fBPn4HUqC4XnPAYnkNlizAcd1hurJrqDtKkDIEy+Y17xr780bBzdZL6JhFm9wCqpXUktNd9JeIYnFiSm1YalSxGPKQmPuSi/JnWsMOtdMUOFKCKigrx7JBmCBtoApcyDO6BRK2Rn6C2TiCnKhblb0ocHZ735j3Hik620EOfu5dRnGXBWe+gqr07Du6BraDVAaIXb/6tYn70X7oNT3rlvkItZGmapCdTFpVn51sWRs4Cy3LoATJ1Gtwo7VxrM7K7vRrczpX3gEOBJPKagKYKH35GLUQhU2nMUOy0115mHYq44aSrTbH5hZJ78iQaguNdJFtS+efYXTyv2gmosuPxF4gYAddsgxjYE/xhKMyFsW/wy35v8FNwp689kmb9OpT6+C+DHYUw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
