travis:
  secure:
    BINSTAR_TOKEN: bBCE/RwN5+pq4NOIDz+AeQdy3AGZ8wJoKjn/lLFvUjOI8ukkJnWjvEqv1PkbAvzhoWPScTqz0nZkxgqGmzkEG1hkBIb9+XR0rw2YphUDWagDWvduFouxVaJOQh5D4toBSsB9LDhJTWGe4zFinBKjyWfSqaFaAEJWmQ4TTPFPWKTSWdM49dsxfum11+Ip4VXZqA5WHAtGCOsMxNrd0Q4/XY+Ah4itEkopDasnO/nLkE/LQEgvKvO5i633Nat7Zkx68/1ea7zI9Rkm6g5lR70FDMvXE+Iknmk5tOdY3ivGR0FaG0ROHXRhijZ/AowpePBHvwBXs72v0Pd6XYsRggKJLe8sC4Gqx6583xor0J/GATS/fC6wYAxRWYX3veX+cI2qYYGIUfy9G8gQ0QWEmkcJJKWV8e8RzP05mt1AWNgXd5FCn/ylpoGA9uHuwYMMaJjwuRzz5phpyWd9u3dzgJUG2xILk8aGxZcL2AOcKfjW2owIJ+tctfzLebqee6ylOyeOD7/aNNRIBJTXhejuMxMKoB0+gRmOiBqTnysMpRPOvqg3bVdFCwsMQSsRt0xq+XXCSAMULEj2oczdATIYofQZQ5uWUsQRqFzMQxgC6892BOD8Whmyby/fYJM8aM1DENEFPxA2gmcezkjaCJHXCu+DVLKiqosGcJM3+6WX8nKyVQw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
